"""remove unique

Revision ID: 010e5d191217
Revises: 7567b74d940f
Create Date: 2019-03-12 21:55:57.766104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010e5d191217'
down_revision = '7567b74d940f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'pesawat_gate_key', 'pesawat', type_='unique')
    op.drop_constraint(u'pesawat_jam_key', 'pesawat', type_='unique')
    op.drop_constraint(u'pesawat_pesawat_key', 'pesawat', type_='unique')
    op.drop_constraint(u'pesawat_status_key', 'pesawat', type_='unique')
    op.drop_constraint(u'pesawat_tujuan_key', 'pesawat', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'pesawat_tujuan_key', 'pesawat', ['tujuan'])
    op.create_unique_constraint(u'pesawat_status_key', 'pesawat', ['status'])
    op.create_unique_constraint(u'pesawat_pesawat_key', 'pesawat', ['pesawat'])
    op.create_unique_constraint(u'pesawat_jam_key', 'pesawat', ['jam'])
    op.create_unique_constraint(u'pesawat_gate_key', 'pesawat', ['gate'])
    # ### end Alembic commands ###
