"""init migrate

Revision ID: 138195358300
Revises: 
Create Date: 2019-04-05 23:26:35.992702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138195358300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maskapai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maskapai', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('penerbangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=80), nullable=False),
    sa.Column('pesawat', sa.Integer(), nullable=True),
    sa.Column('tujuan', sa.String(length=140), nullable=False),
    sa.Column('jam', sa.DateTime(), nullable=False),
    sa.Column('gate', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['pesawat'], ['maskapai.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('penerbangan')
    op.drop_table('roles')
    op.drop_table('maskapai')
    # ### end Alembic commands ###
