"""initial migrate

Revision ID: 7567b74d940f
Revises: 
Create Date: 2019-03-12 20:45:51.016530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7567b74d940f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesawat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=80), nullable=False),
    sa.Column('pesawat', sa.String(length=80), nullable=False),
    sa.Column('tujuan', sa.String(length=140), nullable=False),
    sa.Column('jam', sa.DateTime(), nullable=False),
    sa.Column('gate', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate'),
    sa.UniqueConstraint('jam'),
    sa.UniqueConstraint('kode'),
    sa.UniqueConstraint('pesawat'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('tujuan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesawat')
    # ### end Alembic commands ###
