"""empty message

Revision ID: 91cc8cd97c4a
Revises: df4469213257
Create Date: 2019-04-25 12:45:37.831742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91cc8cd97c4a'
down_revision = 'df4469213257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penerbangan', sa.Column('asal', sa.String(length=140), nullable=False))
    op.add_column('penerbangan', sa.Column('waktu_keberangkatan', sa.DateTime(), nullable=False))
    op.add_column('penerbangan', sa.Column('waktu_kedatangan', sa.DateTime(), nullable=False))
    op.drop_column('penerbangan', 'jam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penerbangan', sa.Column('jam', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('penerbangan', 'waktu_kedatangan')
    op.drop_column('penerbangan', 'waktu_keberangkatan')
    op.drop_column('penerbangan', 'asal')
    # ### end Alembic commands ###
